#!/bin/sh


for f in 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24;
do
    [ -d "$f" ] && \
    (
        cd $f || exit 1
        printf "\nRUNNING DAY %s \n" "$f"
        ./solution.hs
    )
done

exit 0
